# Generated by Django 5.1 on 2024-09-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
