# Generated by Django 5.1 on 2024-09-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0004_order_address_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
